#!/usr/bin/env bash
#  displays the content of the file /etc/passwd
#+ only displays the:
#+ username
#+ group id
#+ Shell full path for the user

while read -r line; do
	echo "$line" | cut -d ":" -f 1,3,6
done < /etc/passwd
